os: osx
language: ruby
rvm:
  - default
  - '2.4.6'
  - '2.5.5'
  - '2.6.3'
  - '2.7.0'
script: bundle exec rspec
matrix:
  include:
    - env: CHECK_RUBIES=1
      script: bundle exec travis_check_rubies
